"""
Metrics calculation utilities
"""

import numpy as np
import pandas as pd
from typing import Union


def calculate_mape(actual: Union[np.ndarray, pd.Series], predicted: Union[np.ndarray, pd.Series]) -> float:
    """
    Calculate Mean Absolute Percentage Error.

    Args:
        actual: Actual values
        predicted: Predicted values

    Returns:
        MAPE as a decimal (e.g., 0.15 for 15%)
    """
    actual = np.array(actual)
    predicted = np.array(predicted)

    # Avoid division by zero
    mask = actual != 0
    if not mask.any():
        return np.inf

    mape = np.mean(np.abs((actual[mask] - predicted[mask]) / actual[mask]))
    return mape


def calculate_rmse(actual: Union[np.ndarray, pd.Series], predicted: Union[np.ndarray, pd.Series]) -> float:
    """
    Calculate Root Mean Square Error.

    Args:
        actual: Actual values
        predicted: Predicted values

    Returns:
        RMSE value
    """
    actual = np.array(actual)
    predicted = np.array(predicted)

    rmse = np.sqrt(np.mean((actual - predicted) ** 2))
    return rmse


def calculate_mae(actual: Union[np.ndarray, pd.Series], predicted: Union[np.ndarray, pd.Series]) -> float:
    """
    Calculate Mean Absolute Error.

    Args:
        actual: Actual values
        predicted: Predicted values

    Returns:
        MAE value
    """
    actual = np.array(actual)
    predicted = np.array(predicted)

    mae = np.mean(np.abs(actual - predicted))
    return mae


def calculate_roi(incremental_revenue: float, promotion_spend: float) -> float:
    """
    Calculate Return on Investment for promotions.

    Args:
        incremental_revenue: Incremental revenue generated
        promotion_spend: Total promotion spend

    Returns:
        ROI as a decimal (e.g., 2.5 for 250% return)
    """
    if promotion_spend == 0:
        return np.inf if incremental_revenue > 0 else 0.0

    roi = incremental_revenue / promotion_spend
    return roi


def calculate_lift(promoted_sales: float, baseline_sales: float) -> float:
    """
    Calculate promotional lift.

    Args:
        promoted_sales: Sales during promotion
        baseline_sales: Expected baseline sales

    Returns:
        Lift multiplier (e.g., 2.5 for 2.5x baseline)
    """
    if baseline_sales == 0:
        return np.inf if promoted_sales > 0 else 0.0

    lift = promoted_sales / baseline_sales
    return lift


def calculate_incremental_volume(promoted_sales: float, baseline_sales: float) -> float:
    """
    Calculate incremental volume generated by promotion.

    Args:
        promoted_sales: Sales during promotion
        baseline_sales: Expected baseline sales

    Returns:
        Incremental units
    """
    return promoted_sales - baseline_sales


def calculate_incremental_margin(
    promoted_sales: float,
    baseline_sales: float,
    unit_margin: float,
    promotion_cost: float
) -> float:
    """
    Calculate net incremental margin from promotion.

    Args:
        promoted_sales: Units sold during promotion
        baseline_sales: Expected baseline units
        unit_margin: Margin per unit
        promotion_cost: Total cost of promotion

    Returns:
        Net incremental margin
    """
    incremental_units = promoted_sales - baseline_sales
    gross_margin = incremental_units * unit_margin
    net_margin = gross_margin - promotion_cost

    return net_margin
